### ISSUE TITLE
Answer validation and consensus

### ISSUE THREAD

**Issue by baioc** [baioc/crowd-sourced#11]
These are two different, yet related, issues we have to deal with:
1. An user may give wrong labels on purpose, make a mistake or simply not be so sure about his answer. We can store these labels anyway for redundancy and choose the ground truth based on some consensus algorithm.
2. A malicious client may send illegal labels to the server (e.g. "my answer to this dog-vs-cat classification problem is `123.45`"). The server could associate single-use tokens to each problem it sends off, and use that to validate the answers it receives.

**Comment by fissoreg** [comment]
Good points.

My take:
1. We can store a count for each option for the labels (like: {"cat": 3, "dog": 0}). For now we can then return the option whose count is maximum, that should be right most of the time.
2. When we receive an answer from the client, we can check the validity before saving to the dataset. If the input is invalid, we simply throw an error. So we make sure that data saved to the database is always valid.

For point 2, I guess we could specify the constraints directly in MongoDB (but I haven't checked the MongoDB API).

**Comment by Rubix982** [comment]
Definitely, these are of concern,

I think,

1. Since we are using MongoDB, it is not difficult to store a dictionary of options that maintains the options for the data, and their frequency
2.  We have constructed a schema with the 'options' field, it would be nice to have a token on the server-side and the client-side, or some sort of id, to trace back to the label we were talking about, and then check on the server-side if the given answer. If it is, we store it in the database accordingly, if not, we throw an error. This error 'bubbles' up from the server-side to the client-side, and we can generate a 'snack bar to showcase that an error has occurred. Snack bars are like dialog boxes in UI, check them out here, https://material-ui.com/components/snackbars/
